### ISSUE TITLE
Especificación de todos los requisitos.

### ISSUE THREAD

**Issue by ricardo-andre-pool-cen** [ricardo-andre-pool-cen/Equipo-0_LIS#72]
## Instrucciones:
*Se deben realizar para todos los requisitos funcionales, de ser necesario, su especificación en diagramas de casos de uso. Se usará la herramienta "Canva" para su construccion.*

### Documentación:
- [ ] Es implementada en un pizarrón virtual en Canva, como nombre del pizarrón será: "EQUIPO#0: Especificación de requisitos."
- [ ] El enlace al pizarrón se debe adjuntar en el Periodo_2, en el documento "Act#3 Requisitos funcionales"
- [ ] Se debe traducir el contenido al ingles en un pizarrón aparte
- [ ] El enlace al pizarrón en ingles se debe adjuntar en el Sprint_2, en el documento "Act#3 Functional requirements"
- [ ] La contribución es registrada en el "daily" de cada responsable.
### Tarea:
- [ ] Se realiza el caso de uso para cada requisito que lo necesite
- [ ] Se justifica la ausencia de caso de uso para ciertos requisitos
- [ ] El formato del caso de uso aplicado es cohesivo y correcto.

**Comment by ricardo-andre-pool-cen** [comment]
Actividad cancelada: cambio de planeacion.
